#ifndef PROTOCOL_H
#define PROTOCOL_H

// Define opcodes for different functions
enum Opcode {
    OPCODE_PING = 0,
    OPCODE_LOGIN = 1,
    OPCODE_REGISTER = 2,
    OPCODE_CHANGE_PASSWORD = 3,
    OPCODE_GET_FRIEND_LIST = 10,
    OPCODE_SEND_FRIEND_REQUEST = 11,
    OPCODE_RESPOND_TO_REQUEST = 12,
    OPCODE_GET_ROOM_LIST = 20,
    OPCODE_GET_PEOPLE_LIST = 21,
    OPCODE_CREATE_ROOM = 22,
    OPCODE_ADD_USER_TO_ROOM = 23,
    OPCODE_REMOVE_USER_FROM_ROOM = 24,
    OPCODE_GET_CONVERSATION = 30,
    OPCODE_SEND_MESSAGE = 31
};

// Define function constants for each opcode
enum Function {
    FUNCTION_PING_AND_GET_USERS = 0,
    FUNCTION_LOGIN = 1,
    FUNCTION_REGISTER = 2,
    FUNCTION_CHANGE_PASSWORD = 3,
    FUNCTION_GET_FRIEND_LIST = 0,
    FUNCTION_SEND_FRIEND_REQUEST = 1,
    FUNCTION_RESPOND_TO_REQUEST = 2,
    FUNCTION_GET_ROOM_LIST = 0,
    FUNCTION_GET_PEOPLE_LIST = 1,
    FUNCTION_CREATE_ROOM = 2,
    FUNCTION_ADD_USER_TO_ROOM = 3,
    FUNCTION_REMOVE_USER_FROM_ROOM = 4,
    FUNCTION_GET_CONVERSATION = 0,
    FUNCTION_SEND_MESSAGE = 1
};

#endif